[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "aipatt"
dynamic = ["version"]
description = "This is AIPATT: AI Powered Assistant Tool for Terminals"
authors = [
    {name = "Somesh Sharma", email = "someshs.ce@gmail.com"}
]
maintainers = [
    {name = "Somesh Sharma", email = "someshs.ce@gmail.com"}
]
requires-python = ">= 3.10"
readme = "README.md"
license = {file = "LICENSE"}
dependencies = [
    "rich",
    "click",
    "psutil",
    "langchain",
    "langgraph",
    "python-dotenv",
    "beautifulsoup4",
    "langchain-core",
    "langchain-ollama",
    "langchain-community",
    'pydantic[email,timezone]',
    "langchain_google_community",
]
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
]
keywords = ["AI", "Terminal", "CMD", "command", "LLM", "Powershell", "Assistant", "Tool"]

[tool.setuptools]
packages = { find = { where = ["."] } }
package-dir = { "" = "." }

[project.scripts]
aipat = "main:cli"

[project.urls]
Repository = "https://github.com/someshsce/aipatt.git"
GitHub = "https://github.com/someshsce/aipatt"
Issues = "https://github.com/someshsce/aipatt/issues"
